---
- block:
    # - name: Update cache
    #   apt: update_cache=yes
    #   ignore_errors: yes

    - name: Install certutil dependencies
      package:
        state: present
        name:
          - wget
          - libnss3-tools

    - name: Download mkcert (v1.3.0) from github release
      get_url:
        url: https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-amd64
        dest: /usr/local/bin/mkcert
        mode: '0755'

    - name: Install the local CA in the system trust store.
      shell: mkcert -install

  become: yes
  become_user: root

- name: Generating SSL certificates for domains
  shell: mkcert localhost provisioner.com 127.0.0.1 ::1
  args:
    chdir: '{{ansible_env.HOME}}'