---
- block:
    - name: "Update cache"
      apt: 
        update_cache: yes
        
    - name: Change locale
      command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
      notify: update tzdata

    - name: Install common apps
      package: 
        state: present
        name:
          - git
          - vim
          - redis
          - sqlite3

  become: yes
  become_user: root
